/**
 * Reading tours: ordered "Start here" paths through a codebase. Each step points
 * at a file + line with a short note. Tours are authored manually or generated by
 * the terminal agent (which writes a scratch tour Reado imports). Persisted in
 * `.reado/tours.json` (Reado owns it). The purest expression of "reading code you
 * didn't write".
 */
import { create } from "zustand";
import { log, safeError } from "./logger";
import { readFile, createFile, writeFile } from "./api";
import { dispatchToAgent } from "./agents";
import { useProject } from "./store";
import { useDocInfo } from "./docInfo";

export interface TourStep {
  /** Project-relative, forward-slashed path. */
  file: string;
  /** 1-based line. */
  line: number;
  note: string;
}
export interface Tour {
  id: string;
  name: string;
  steps: TourStep[];
}

const STORE = ".reado/tours.json";
const AI_SCRATCH = ".reado/ai-tour.json";
let seq = 0;
const newId = () => `tour_${Date.now().toString(36)}_${seq++}`;

const delay = (ms: number) => new Promise((r) => setTimeout(r, ms));
let aiToken = 0;

async function load(root: string): Promise<Tour[]> {
  const c = await readFile(root, STORE).catch(() => null);
  if (c && c.kind === "text") {
    try {
      return JSON.parse(c.text) as Tour[];
    } catch (e) {
      log.warn("tours: corrupt store, treating as empty", { error: safeError(e) });
    }
  }
  return [];
}

async function save(root: string, tours: Tour[]) {
  await createFile(root, STORE).catch(() => {});
  await writeFile(root, STORE, JSON.stringify(tours, null, 2)).catch(() => {});
}

interface ToursState {
  tours: Tour[];
  /** The running tour + current step index, or null. */
  running: { tourId: string; index: number } | null;
  /** True while an AI tour is being generated. */
  generating: boolean;
  load: (root: string) => Promise<void>;
  createTour: (root: string, name: string) => void;
  removeTour: (root: string, id: string) => void;
  addStepHere: (root: string, tourId: string, note: string) => void;
  removeStep: (root: string, tourId: string, index: number) => void;
  start: (tourId: string) => void;
  stop: () => void;
  go: (delta: number) => void;
  generate: (root: string) => void;
}

export const useTours = create<ToursState>((set, get) => ({
  tours: [],
  running: null,
  generating: false,
  load: async (root) => set({ tours: await load(root), running: null }),

  createTour: (root, name) => {
    const tours = [...get().tours, { id: newId(), name, steps: [] }];
    set({ tours });
    void save(root, tours);
  },
  removeTour: (root, id) => {
    const tours = get().tours.filter((t) => t.id !== id);
    set({ tours, running: get().running?.tourId === id ? null : get().running });
    void save(root, tours);
  },
  addStepHere: (root, tourId, note) => {
    const { view } = useDocInfo.getState();
    const active = useProject.getState().active;
    if (!view || !active) return;
    const line = view.state.doc.lineAt(view.state.selection.main.head).number;
    const rel = active.startsWith(root) ? active.slice(root.length).replace(/^[\\/]+/, "") : active;
    const tours = get().tours.map((t) =>
      t.id === tourId ? { ...t, steps: [...t.steps, { file: rel.replace(/\\/g, "/"), line, note }] } : t,
    );
    set({ tours });
    void save(root, tours);
  },
  removeStep: (root, tourId, index) => {
    const tours = get().tours.map((t) =>
      t.id === tourId ? { ...t, steps: t.steps.filter((_, i) => i !== index) } : t,
    );
    set({ tours });
    void save(root, tours);
  },

  start: (tourId) => {
    const tour = get().tours.find((t) => t.id === tourId);
    if (!tour || tour.steps.length === 0) return;
    set({ running: { tourId, index: 0 } });
    openStep(tour.steps[0]);
  },
  stop: () => set({ running: null }),
  go: (delta) => {
    const running = get().running;
    if (!running) return;
    const tour = get().tours.find((t) => t.id === running.tourId);
    if (!tour) return;
    const index = Math.max(0, Math.min(tour.steps.length - 1, running.index + delta));
    set({ running: { ...running, index } });
    openStep(tour.steps[index]);
  },

  generate: (root) => {
    const mine = ++aiToken;
    set({ generating: true });
    void dispatchToAgent(
      `Create a guided reading tour of THIS repository for someone new to it: an ` +
        `ordered list of steps, each pointing at a file + line with a one-sentence note ` +
        `on what to read there and why (start at the entry points, then key modules). ` +
        `Write JSON {"name": "...", "steps": [{"file": "rel/path", "line": 1, "note": ` +
        `"..."}]} to \`${AI_SCRATCH}\`. Do not modify any other file.`,
    );
    void (async () => {
      for (let i = 0; i < 60; i++) {
        await delay(1500);
        if (aiToken !== mine) return;
        const c = await readFile(root, AI_SCRATCH).catch(() => null);
        if (c && c.kind === "text" && c.text.trim()) {
          try {
            const parsed = JSON.parse(c.text) as { name?: string; steps?: TourStep[] };
            if (Array.isArray(parsed.steps) && parsed.steps.length) {
              const tour: Tour = {
                id: newId(),
                name: parsed.name || "AI tour",
                steps: parsed.steps,
              };
              const tours = [...get().tours, tour];
              set({ tours, generating: false });
              void save(root, tours);
              return;
            }
          } catch {
            /* keep polling for valid JSON */
          }
        }
      }
      if (aiToken === mine) set({ generating: false });
    })();
  },
}));

function openStep(step: TourStep) {
  const root = useProject.getState().root;
  useProject.getState().open(`${root}/${step.file}`, step.line);
}
