/**
 * Reading tours: ordered "Start here" paths through a codebase. Each step points
 * at a file + line with a short note. Tours are authored manually or generated by
 * the terminal agent (which writes a scratch tour Reado imports). Persisted in
 * `.reado/tours.json` (Reado owns it). The purest expression of "reading code you
 * didn't write".
 */
import { create } from "zustand"
import { runAgentTask, useAgentTasks } from "./agentTask"
import { createFile, readFile, writeFile } from "./api"
import { useDocInfo } from "./docInfo"
import { log, safeError } from "./logger"
import { useProject } from "./store"

export interface TourStep {
  /** Project-relative, forward-slashed path. */
  file: string
  /** 1-based line. */
  line: number
  note: string
}
export interface Tour {
  id: string
  name: string
  steps: TourStep[]
}

const STORE = ".reado/tours.json"
const AI_SCRATCH = ".reado/ai-tour.json"
let seq = 0
const newId = () => `tour_${Date.now().toString(36)}_${seq++}`

/** One task slot: generating again supersedes the run before it. */
const TASK = "tours"

async function load(root: string): Promise<Tour[]> {
  const c = await readFile(root, STORE).catch(() => null)
  if (c && c.kind === "text") {
    try {
      return JSON.parse(c.text) as Tour[]
    } catch (e) {
      log.warn("tours: corrupt store, treating as empty", { error: safeError(e) })
    }
  }
  return []
}

async function save(root: string, tours: Tour[]) {
  await createFile(root, STORE).catch(() => {})
  await writeFile(root, STORE, JSON.stringify(tours, null, 2)).catch(() => {})
}

interface ToursState {
  tours: Tour[]
  /** The running tour + current step index, or null. */
  running: { tourId: string; index: number } | null
  /** True while an AI tour is being generated. */
  generating: boolean
  load: (root: string) => Promise<void>
  createTour: (root: string, name: string) => void
  removeTour: (root: string, id: string) => void
  addStepHere: (root: string, tourId: string, note: string) => void
  removeStep: (root: string, tourId: string, index: number) => void
  start: (tourId: string) => void
  stop: () => void
  go: (delta: number) => void
  generate: (root: string) => void
  /** Stop watching for an in-flight AI tour. */
  cancelGenerate: () => void
}

export const useTours = create<ToursState>((set, get) => ({
  tours: [],
  running: null,
  generating: false,
  load: async (root) => set({ tours: await load(root), running: null }),

  createTour: (root, name) => {
    const tours = [...get().tours, { id: newId(), name, steps: [] }]
    set({ tours })
    void save(root, tours)
  },
  removeTour: (root, id) => {
    const tours = get().tours.filter((t) => t.id !== id)
    set({ tours, running: get().running?.tourId === id ? null : get().running })
    void save(root, tours)
  },
  addStepHere: (root, tourId, note) => {
    const { view } = useDocInfo.getState()
    const active = useProject.getState().active
    if (!view || !active) return
    const line = view.state.doc.lineAt(view.state.selection.main.head).number
    const rel = active.startsWith(root) ? active.slice(root.length).replace(/^[\\/]+/, "") : active
    const tours = get().tours.map((t) =>
      t.id === tourId
        ? { ...t, steps: [...t.steps, { file: rel.replace(/\\/g, "/"), line, note }] }
        : t,
    )
    set({ tours })
    void save(root, tours)
  },
  removeStep: (root, tourId, index) => {
    const tours = get().tours.map((t) =>
      t.id === tourId ? { ...t, steps: t.steps.filter((_, i) => i !== index) } : t,
    )
    set({ tours })
    void save(root, tours)
  },

  start: (tourId) => {
    const tour = get().tours.find((t) => t.id === tourId)
    if (!tour || tour.steps.length === 0) return
    set({ running: { tourId, index: 0 } })
    openStep(tour.steps[0])
  },
  stop: () => set({ running: null }),
  go: (delta) => {
    const running = get().running
    if (!running) return
    const tour = get().tours.find((t) => t.id === running.tourId)
    if (!tour) return
    const index = Math.max(0, Math.min(tour.steps.length - 1, running.index + delta))
    set({ running: { ...running, index } })
    openStep(tour.steps[index])
  },

  generate: (root) => {
    set({ generating: true })
    void (async () => {
      const out = await runAgentTask({
        id: TASK,
        labelKey: "tours.panel",
        prompt:
          `Create a guided reading tour of THIS repository for someone new to it: an ` +
          `ordered list of steps, each pointing at a file + line with a one-sentence note ` +
          `on what to read there and why (start at the entry points, then key modules). ` +
          `Write JSON {"name": "...", "steps": [{"file": "rel/path", "line": 1, "note": ` +
          `"..."}]} to \`${AI_SCRATCH}\`. Do not modify any other file.`,
        poll: async () => {
          const c = await readFile(root, AI_SCRATCH)
          return c.kind === "text" ? c.text : null
        },
        // The agent writes this file as it goes, so a payload that doesn't parse
        // yet — or has no steps yet — means "keep watching", not "broken".
        parse: (text) => {
          let parsed: { name?: string; steps?: TourStep[] }
          try {
            parsed = JSON.parse(text) as { name?: string; steps?: TourStep[] }
          } catch {
            return undefined
          }
          if (!Array.isArray(parsed.steps) || !parsed.steps.length) return undefined
          return { id: newId(), name: parsed.name || "AI tour", steps: parsed.steps } as Tour
        },
      })
      if (out.status === "cancelled") return set({ generating: false })
      if (out.status !== "done") return set({ generating: false })
      const tours = [...get().tours, out.value]
      set({ tours, generating: false })
      void save(root, tours)
    })()
  },
  cancelGenerate: () => useAgentTasks.getState().cancel(TASK),
}))

function openStep(step: TourStep) {
  const root = useProject.getState().root
  useProject.getState().open(`${root}/${step.file}`, step.line)
}
